### ISSUE TITLE
Checkpoint #2

### ISSUE THREAD

**Issue by dmueller3** [dmueller3/FantasyFootballScheduler#4]
@pawaitemadisoncollege

Database designed and created, at least one DAO with full CRUD (create, read, update, delete) implemented with Hibernate, DAO is fully unit tested, Log4J is implemented (no System.out.printlns). Week 7.

**Comment by pawaitemadisoncollege** [comment]
Hi @dmueller3! You've made some good early progress with your indie project!  

**Database designed and created** 

I can see sql for the Teams table, which looks good. 

- [ ] Can you share an erd so that I can review the full database design? The database view in IntelliJ can produce this if you don't have a preferred way of generating it already.

**DAO**

Implemented on the Teams table and unit tested.

- [ ] Next step will be to implement the generic dao and add tests for the rest of your entities, especially testing the relationships. 

**Log4J is implemented (no System.out.printlns)**

No printlns found when searching the repo. :) 

**Time log and Plan**

This is up-to-date through week 6 (with items checked off in the plan).

- [ ] Time to add more specific tasks for the upcoming weeks, such as the generic dao, user table (entity and tests), adding users after the sign up in cognito, etc. 

**Checkpoint 2: not yet** - just related to the erd. I'd like to review that sooner than later.

**Comment by dmueller3** [comment]
@pawaitemadisoncollege sorry for the delay. Please see my ERD attached: 
![image](https://github.com/user-attachments/assets/6fc3c9ce-1f18-4714-9728-753caac28ad8)

**Comment by pawaitemadisoncollege** [comment]
Thanks for sharing this @dmueller3. One question - will each user have only one schedule?  Asking because I was expecting to see a user table, but it's possible you don't need it (sorry if we chatted about this already and I've forgotten).

**Comment by dmueller3** [comment]
No- you're right! Here's the updated diagram with the user table!
@pawaitemadisoncollege 
![image](https://github.com/user-attachments/assets/80cabbb5-c9df-41eb-9bf8-5fbf594433e8)

**Comment by pawaitemadisoncollege** [comment]
Looks good now! @dmueller3 

checkpoint 2: met

**Comment by dmueller3** [comment]
Thanks!
